### PR TITLE
chore(name): Rename to react-talend-forms

### PR DESCRIPTION
**Pull request by talend-glorieux**

### CODE REVIEW

**Comment by talend-glorieux** [comment]
Should I also rename the GitHub project?

**Comment by jmfrancois** [comment]
don't forget travis also

**Comment by jmfrancois** [comment]
https://github.com/Talend/react-bootstrap-forms/search?utf8=%E2%9C%93&q=react-bootstrap-forms
There are missing stuff, sorry my review is incomplete

**Comment by talend-glorieux** [comment]
Yep forgot the readme ;)

**Pull request merged**
